---
- name: Template the hadoop-env config file
  ansible.builtin.template:
    src: /opt/manager/templates/hadoop-env.j2
    dest: /opt/hadoop/etc/hadoop/hadoop-env.sh
    force: yes

- name: Template the .bashrc file
  ansible.builtin.template:
    src: /opt/manager/templates/.bashrc.j2
    dest: ~/.bashrc
    force: yes

- name: Template the core-site.xml file
  ansible.builtin.template:
    src: /opt/manager/templates/core-site.j2
    dest: /opt/hadoop/etc/hadoop/core-site.xml
    force: yes

- name: Template the hdfs-site.xml file
  ansible.builtin.template:
    src: /opt/manager/templates/hdfs-site.j2
    dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
    force: yes

- name: Template the mapred-site.xml file
  ansible.builtin.template:
    src: /opt/manager/templates/mapred-site.j2
    dest: /opt/hadoop/etc/hadoop/mapred-site.xml
    force: yes

- name: Template the yarn-site.xml file
  ansible.builtin.template:
    src: /opt/manager/templates/yarn-site.j2
    dest: /opt/hadoop/etc/hadoop/yarn-site.xml
    force: yes
